openapi: 3.0.0
info:
  title: Medical Appointment API
  version: 1.0.0
  description: API para gerenciamento de pacientes, consultas e transcrição de áudios.

tags:
  - name: Appointments
    description: Endpoints relacionados a consultas médicas
  - name: Patients
    description: Endpoints relacionados a pacientes
  - name: Transcription and Resume
    description: Endpoints relacionados à transcrição de áudios e resumos

paths:
  /patients/{cpf}/appointments:
    get:
      tags:
        - Appointments
      summary: Lista todas as consultas de um paciente
      operationId: getAppointments
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de consultas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CreateAppointment'
        '400':
          description: Erro na solicitação
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      tags:
        - Appointments
      summary: Cria uma nova consulta
      operationId: createAppointment
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Appointment'
      responses:
        '201':
          description: Consulta criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Erro na solicitação
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /appointments/{appointmentId}:
    get:
      tags:
        - Appointments
      summary: Obtém uma consulta pelo ID
      operationId: getAppointmentById
      parameters:
        - name: appointmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes da consulta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '404':
          description: Consulta não encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    patch:
      tags:
        - Appointments
      summary: Atualiza uma consulta existente
      operationId: updateAppointment
      parameters:
        - name: appointmentId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAppointment'
      responses:
        '200':
          description: Consulta atualizada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
        '400':
          description: Erro na solicitação
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Consulta não encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    delete:
      tags:
        - Appointments
      summary: Deleta uma consulta pelo ID
      operationId: deleteAppointment
      parameters:
        - name: appointmentId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Consulta deletada com sucesso
        '400':
          description: Erro na solicitação
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Consulta não encontrada
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /patients:
    get:
      tags:
        - Patients
      summary: Lista todos os pacientes
      operationId: getPatients
      responses:
        '200':
          description: Lista de pacientes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Patient'
        '400':
          description: Erro na solicitação
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      tags:
        - Patients
      summary: Cria um novo paciente
      operationId: createPatient
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '201':
          description: Paciente criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '400':
          description: Erro na solicitação
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /patients/{cpf}:
    get:
      tags:
        - Patients
      summary: Obtém um paciente pelo CPF
      operationId: getPatientById
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalhes do paciente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '404':
          description: Paciente não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    patch:
      tags:
        - Patients
      summary: Atualiza um paciente existente
      operationId: updatePatient
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Patient'
      responses:
        '200':
          description: Paciente atualizado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Patient'
        '400':
          description: Erro na solicitação
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Paciente não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    delete:
      tags:
        - Patients
      summary: Deleta um paciente pelo CPF
      operationId: deletePatient
      parameters:
        - name: cpf
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Paciente deletado com sucesso
        '400':
          description: Erro na solicitação
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Paciente não encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /resume:
    post:
      tags:
        - Transcription and Resume
      summary: Gera um resumo de uma consulta a partir de uma gravação de áudio
      operationId: OfAudioRecording
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audioFile:
                  type: string
                  format: binary
      responses:
        '200':
          description: Resumo gerado com sucesso
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: Erro na solicitação
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    CreateAppointment:
      type: object
      properties:
        date:
          type: string
          format: date-time
        notes:
          type: array
          items:
            type: string
        prescriptions:
          type: array
          items:
            type: string

    Appointment:
      type: object
      properties:
        id:
          type: string
        date:
          type: string
          format: date-time
        patient:
          $ref: '#/components/schemas/Patient'
        notes:
          type: array
          items:
            type: string
        prescriptions:
          type: array
          items:
            type: string

    Patient:
      type: object
      properties:
        cpf:
          type: string
        name:
          type: string
        birthDate:
          type: string
          format: date
        gender:
          type: string
        profession:
          type: string
        allergies:
          type: array
          items:
            type: string
        comorbidities:
          type: array
          items:
            type: string
        continuosMedications:
          type: array
          items:
            type: string